apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-ui
  template:
    metadata:
      labels:
        app: weather-ui
    spec:
      serviceAccountName: default
      containers:
        - name: weather-ui
          image: us-central1-docker.pkg.dev/weather-ai-dashboard/weather-repo/weather-ui:v2
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              valueFrom:
                secretKeyRef:
                  name: weather-ui-secret
                  key: REACT_APP_API_URL
